# Generated by Django 5.0.6 on 2024-07-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('descripcion2', models.TextField()),
                ('precio', models.IntegerField()),
                ('duracion', models.CharField(max_length=50)),
                ('incluye', models.TextField()),
            ],
        ),
    ]
