# Generated by Django 5.0.6 on 2024-07-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Strongapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='imagen',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
