# Generated by Django 5.0.6 on 2024-07-05 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Strongapp', '0004_alter_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
