# Generated by Django 5.0.6 on 2024-07-05 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Strongapp', '0007_alter_usuario_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
